name:                maxel
version:             0.1.0.0
github:              "runarorama/maxel"
license:             BSD3
author:              "Rúnar Bjarnason"
maintainer:          "runar@bjarnason.is"
copyright:           "2018 Rúnar Bjarnason"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/maxel#readme>

dependencies:
- base >= 4.7 && < 5
- multiset

library:
  source-dirs: src

tests:
  maxel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maxel
